// DEV-ONLY DEMO ROUTE — delete before opening the PR.
// This stands in for the real backend so /fleet renders with data on localhost.
import { NextResponse } from 'next/server';
import type { FleetResponse } from '@/types/fleet';

const fixture: FleetResponse = {
  drivers: [
    {
      id: 'd1',
      name: 'Adaeze Okafor',
      phone: '+2348011110001',
      vehicleType: 'Cargo Van',
      vehiclePlate: 'LAG-114-AB',
      status: 'on_delivery',
      rating: 4.9,
      activeDeliveries: 2,
      completedDeliveries: 312,
      location: { lat: 6.5244, lng: 3.3792, updatedAt: new Date().toISOString() },
    },
    {
      id: 'd2',
      name: 'Tunde Bello',
      phone: '+2348011110002',
      vehicleType: 'Box Truck',
      vehiclePlate: 'LAG-227-CD',
      status: 'active',
      rating: 4.7,
      activeDeliveries: 1,
      completedDeliveries: 218,
      location: { lat: 6.6018, lng: 3.3515, updatedAt: new Date().toISOString() },
    },
    {
      id: 'd3',
      name: 'Ngozi Eze',
      phone: '+2348011110003',
      vehicleType: 'Bike',
      vehiclePlate: 'LAG-339-EF',
      status: 'idle',
      rating: 4.6,
      activeDeliveries: 0,
      completedDeliveries: 84,
      location: { lat: 6.4654, lng: 3.4064, updatedAt: new Date().toISOString() },
    },
    {
      id: 'd4',
      name: 'Ifeanyi Obi',
      phone: '+2348011110004',
      vehicleType: 'Cargo Van',
      vehiclePlate: 'ABJ-441-GH',
      status: 'on_delivery',
      rating: 4.8,
      activeDeliveries: 3,
      completedDeliveries: 401,
      location: { lat: 9.0579, lng: 7.4951, updatedAt: new Date().toISOString() },
    },
    {
      id: 'd5',
      name: 'Halima Yusuf',
      phone: '+2348011110005',
      vehicleType: 'Bike',
      vehiclePlate: 'ABJ-553-IJ',
      status: 'active',
      rating: 4.5,
      activeDeliveries: 1,
      completedDeliveries: 152,
      location: { lat: 9.0764, lng: 7.3986, updatedAt: new Date().toISOString() },
    },
    {
      id: 'd6',
      name: 'Chuka Mensah',
      phone: '+2348011110006',
      vehicleType: 'Cargo Van',
      vehiclePlate: 'PHC-665-KL',
      status: 'offline',
      rating: 4.3,
      activeDeliveries: 0,
      completedDeliveries: 67,
      location: { lat: 4.8156, lng: 7.0498, updatedAt: new Date().toISOString() },
    },
    {
      id: 'd7',
      name: 'Sade Williams',
      phone: '+2348011110007',
      vehicleType: 'Bike',
      vehiclePlate: 'LAG-777-MN',
      status: 'on_delivery',
      rating: 4.9,
      activeDeliveries: 1,
      completedDeliveries: 290,
      location: { lat: 6.5244, lng: 3.3892, updatedAt: new Date().toISOString() },
    },
    {
      id: 'd8',
      name: 'Olumide Akinwale',
      phone: '+2348011110008',
      vehicleType: 'Box Truck',
      vehiclePlate: 'IBA-889-OP',
      status: 'idle',
      rating: 4.4,
      activeDeliveries: 0,
      completedDeliveries: 122,
      location: { lat: 7.3775, lng: 3.947, updatedAt: new Date().toISOString() },
    },
  ],
  summary: {
    totalDrivers: 8,
    activeDrivers: 2,
    onDelivery: 3,
    idle: 2,
    offline: 1,
  },
};

export async function GET() {
  return NextResponse.json(fixture);
}
